export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const CHANGE_WEBSITE_DIVISION = 'CHANGE_WEBSITE_DIVISION';
export const SELECT_TAG = 'SELECT_TAG';
export const ARTICLES_FILTER = 'ARTICLES_FILTER';
